spring:
  application:
    name: Backend

  security:
    user:
      name: user
      password: 123456

  datasource:
    url: jdbc:mysql://localhost:3306/cloudbalance
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

app:
  secret-key : safdkjbnvshbhkkjbvdsknbkbvdsvkj43t
  expiration:
    refreshToken: 259200000
    accessToken: 900000